### ISSUE TITLE
some env setting needed for useSSL=false....

### ISSUE THREAD

**Issue by mgttt** [eternnoir/activiti#10]
WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by bartcallaerts** [comment]
I've got the exact same issue here. I also see that de image will run with the MySql database by default...

**Comment by shantanuo** [comment]
same issue here as well.
