### ISSUE TITLE
activiti 5.20.0 - bugfix release

### ISSUE THREAD

**Issue by ptica** [eternnoir/activiti#8]
`We’ve just released Activiti 5.20.0. This is a bugfix release (mainly fixing the bug around losing message and signal start event subscriptions on process definition redeployment, see ACT-4117).
`

**Comment by lorenzvth7** [comment]
`docker pull eternnoir/activiti:5.20.0` or `docker pull eternnoir/activiti:5.19.0` didnt' seem to work for me

**Comment by eternnoir** [comment]
Already upload 5.20.0 & 5.21.0 to docker hub.
